function [copperLoss,strandNumber,strandWidth,strandHeight] = roebelAnalysis(axialLength,slotNumber,slotWidth,slotHeight)
% Parameters
Iph=1860;% in A % phase current rms
wedgeHeight = 5.5; % in mm
slotSpacerHeight = 5.5; % in mm % spacer between top and bottom coils
mainInsulationThickness = 3; % in mm
slotSpringThickness = 1; % in mm
slotFillingTolerance = 0.2; % in mm % not cutting tolerance, used for coil production

length=2*axialLength*slotNumber;     % in m % Total copper length in active region
total_height=(slotHeight - wedgeHeight - slotSpacerHeight - slotSpringThickness)...
              /2 - 2*mainInsulationThickness; % in m % slot copper height for single coil without main isolation

strandInsulation=0.22e-3;   % in m % strand-to-strand insulation length
total_width=slotWidth - 2*slotFillingTolerance;    % in m % total copper width with isolation

numberOfhorizontalStrand=2; % number of  horizontal strands 
width_strand=(total_width - 2*mainInsulationThickness)/2 - strandInsulation; % in m % strand width 

ro=2.0968e-8;         % in Ohm*m  % resistivity at 125 degree
k=2.2;                % unitless % (endwinding+active)/active region ratio % empirical 
mu0=4*pi*1e-7;        % permeability
f=50;                 % in 1/s % frequency of the current

% Arrays
height_strand_X=[];  % in m  % array recording different strand heights 
                     % according to number of vertical...
                     % strands and slot copper height for single copper
Pdc_tot=[];          % in kW % Total DC loss consisting both top and 
                     % bottom windings
P_eddy_tot=[];       % in kW % Total Eddy loss consisting both top and
                     % bottom windings.  Not include circulation current 
                     % which is eliminated by roebel transposition
strand=[];           % array recording the number of vertical strands 
                     % numberOfverticalStrand
TopBottom=[];        % Eddy losses ratio of top to bottom coils

for numberOfverticalStrand=10:1:66 % indexing number of vertical strands  
Bmax=(2*mu0*Iph)/(total_width); % Maximum tangential B, generated by coils
                                % We have two coils, called top and bottom
                                % Top coil is the coil close to airgap
                                % Bottom coil is the coil far away from 
                                % to airgap
                                
B=linspace(0,Bmax,numberOfverticalStrand*2); % B for each strand 
                             % First half of the array belongs to top   
                             % Latter half of the array belongs to bottom 


Ke= pi^2/(6*ro);                % The constant for eddy losses

height_strand=(total_height/numberOfverticalStrand)-strandInsulation; %corrected with below one
                                % the height for strand according to 
                                % strand number
% height_strand=(total_hei ght-(numberOfverticalStrand+1)*insulation)/(numberOfverticalStrand+1);

DC_resistance=ro*length*k/((width_strand*height_strand)); 
                                % DC resistance for unit area included both
                                % active and endwinding region
                                % for both top and bottom coil
DC_resistance=DC_resistance/(numberOfverticalStrand*numberOfhorizontalStrand);
                                % DC resistance for unit area included both
                                % active and endwinding region
                                % for both top and bottom coil
                                                              
Pdc=Iph^2*DC_resistance;        % DC losses for the indexed strand


volume=numberOfhorizontalStrand*width_strand*height_strand*length; 
                                % strand volume for each vertical level
                                % included 2 horizontal strand

Peddy= Ke*B.^2*f^2*height_strand^2*volume;
                                % Eddy losses for each vertical level

Pdc_tot=[Pdc_tot Pdc];               % Total DC losses for the
                                     % indexed strand number

P_eddy_tot=[P_eddy_tot sum(Peddy)];  % Total Eddy losses for the
                                     % indexed strand number

                                     
TopBottom=[TopBottom ...
    sum(Peddy(1:numberOfverticalStrand/2))/...
    sum(Peddy(numberOfverticalStrand/2+1:end))];
                                     % Eddy losses ratio of top 
                                     % to bottom coils
                
strand=[strand numberOfverticalStrand]; 
                       % array recording the number of vertical strands 
                       % numberOfverticalStrand
height_strand_X=[height_strand_X height_strand];
                     % in m  % array recording different strand heights 
                     % according to number of vertical...
                     % strands and slot copper height for single copper

end
totalCopperLoss = Pdc_tot + P_eddy_tot;
[minimumLoss, index] = min(totalCopperLoss);
copperLoss = minimumLoss;
strandNumber = strand(index);
strandWidth = width_strand;
strandHeight = height_strand_X(index);
end